### ISSUE TITLE
Use of Normalizing Flow

### ISSUE THREAD

**Issue by subClassy** [tianyuan168326/SelfC#1]
Hi, read your paper and it was quite good. I am planning to use your paper as a baseline for one of my course projects. For that purpose, I was wondering if you guys thought about using Normalizing Flows to model the conditional probability `p(f_h|f_l)`. Something similar to Zhu, Yiming et al. “High-frequency Normalizing Flow for Image Rescaling.”

**Comment by tianyuan168326** [comment]
Currently, I am busy and do not try it. But, I can recommend you a paper about normalizing flow-based video compression.
CANF-VC: Conditional Augmented Normalizing Flows for Video Compression
https://arxiv.org/abs/2207.05315?context=eess

**Comment by subClassy** [comment]
Alright, I will give this a read. Thankyou so much!
